### ISSUE TITLE
Example should use maxminddb

### ISSUE THREAD

**Issue by oschwald** [duo-labs/neustar2mmdb#1]
It is a bit pointless to use the private `_get` method from the geoip2 module when you could just use [maxminddb](https://pypi.python.org/pypi/maxminddb) directly.

**Comment by kylelady** [comment]
The thought behind using `_get()` came from our workflow, where it was easier to keep using the geoip2 module instead of having to get another module installed in our production environment. maxminddb is surely another option, though. I'll add it to the docs. Thanks!

**Comment by oschwald** [comment]
`geoip2` is just a wrapper around `maxminddb` that provides model objects instead of a dictionary. If you have `geoip2` installed, you have `maxminddb` installed. See [geoip2.databases](https://github.com/maxmind/GeoIP2-python/blob/master/geoip2/database.py#L12).

**Comment by kylelady** [comment]
Ah, I didn't look into how `geoip2`  was implemented. I've updated the docs in @ad65d9d to present `maxminddb` first.
